import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Navbar'
import { Footer } from '@/Components/Footer'
import Download from '@/Components/Download'
import About from '@/Components/About'
import FeedBack from '@/Components/Feedback'

import Location from '@/Components/Location'
import { Developers } from '@/Components/Developers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Download/>
        <About/>
        <Developers/>
        <Location/>
        <FeedBack/>
        

        <main className='relative overflow-hidden '> 
        {children}
        <Footer/>
        </main>
        
       
      </body>
    </html>
  )
}